name: mgasa-cloud-viewer
region: nyc
services:
- name: web
  github:
    repo: MGASALUCAS/remote_rtsp
    branch: main
    deploy_on_push: true
  run_command: gunicorn --bind 0.0.0.0:$PORT --workers 2 --threads 2 --timeout 120 app:app
  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  health_check:
    http_path: /health
    initial_delay_seconds: 30
    period_seconds: 10
    timeout_seconds: 5
    success_threshold: 1
    failure_threshold: 3
  envs:
  - key: PORT
    value: "8080"
    scope: RUN_TIME
  - key: PYTHONUNBUFFERED
    value: "1"
    scope: RUN_TIME

